classDiagram
    class Estudiante {
        -id: int
        -nombre: string
        -email: string
        -carrera: string
        +registrar(): void
        +editarPerfil(): void
        +consultarCursosDisponibles(): List<Curso>
        +consultarCursosMatriculados(): List<Curso>
    }
 
    class Curso {
        -codigo: string
        -nombre: string
        -creditos: int
        +matricular(): void
        +retirar(): void
    }
  

    class Periodo {
        -año: int
        -nombre: string
        -activo: booleano
        +iniciarPeriodo(): void
        +finalizarPeriodo(): void
    }

    class PeriodoCurso {
        -idCurso: string
        -idPeriodo: int
        -idProfesor: int
        -horario: string
        +asignarProfesor(): void
        +definirHorario(): void
    }
  
    Estudiante "1" --> "*" Curso : matrícula
    Curso  "1" --> "*" Periodo : ofrecido en 
    Periodo  "1" --> "*" PeriodoCurso : contiene 
   